const projects = [
  {
    name: "TODOTECH",
    information:
      "E-commerce focused on the sale of pre-assembled computers, components and peripherals.",
    tools: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "SASS",
      "Photoshop",
      "Illustrator",
      "git",
      "Figma",
      "Visual Studio Code",
      "Netlify",
    ],
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1693907606/todotech_xeasla.png",
    logo: "https://res.cloudinary.com/diruiumfk/image/upload/v1693585257/todotech-logo_whcfxr.png",
    url: "https://todotech.netlify.app/",
    moreInfo: "/work/todotech",
    repository: "https://github.com/juanigarciadev/proyecto-TODOTECH",
    badge: false,
    tag: "// E-commerce",
  },
  {
    name: "BEYOND IMAGINATION",
    information:
      "E-commerce of an online learning academy related to programming.",
    tools: [
      "ReactJS",
      "HTML5",
      "CSS3",
      "Firebase",
      "SASS",
      "git",
      "Photoshop",
      "Illustrator",
      "Figma",
      "Visual Studio Code",
      "Vercel",
    ],
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1693254750/beyond-imagination_p25riu.png",
    logo: "https://res.cloudinary.com/diruiumfk/image/upload/v1680216082/beyond-imagination-full_jxvtga.png",
    url: "https://beyond-imagination.vercel.app/",
    moreInfo: "/work/beyond-imagination",
    repository: "https://github.com/juanigarciadev/first-react-app",
    badge: false,
    tag: "// E-commerce",
  },
  {
    name: "zolution",
    information: "Own web design and development agency in creation.",
    tools: [
      "ReactJS (Vite)",
      "HTML5",
      "CSS3",
      "SASS",
      "git",
      "Photoshop",
      "Illustrator",
      "Figma",
      "Visual Studio Code",
      "Vercel",
    ],
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1693254749/zolution_dhcyxw.png",
    logo: "https://res.cloudinary.com/diruiumfk/image/upload/v1684452439/zolution-logo_uekblv.svg",
    url: "https://zolution.vercel.app/",
    moreInfo: "/work/zolution",
    repository: "https://github.com/juanigarciadev/zolution",
    badge: "Working in...",
    tag: "// Design and development agency",
  },
  {
    name: "My portfolio",
    information:
      "Personal website to show my progress in the programming field (learned technologies, projects and personal publications).",
    tools: [
      "ReactJS (Vite)",
      "HTML5",
      "CSS3",
      "Tailwind",
      "git",
      "Photoshop",
      "Illustrator",
      "Visual Studio Code",
      "Vercel",
    ],
    img: "https://res.cloudinary.com/diruiumfk/image/upload/v1694627377/portfolio_j7dmf2.png",
    logo: null,
    url: "https://juanigarciadev.vercel.app/",
    moreInfo: "/work/my-portfolio",
    repository: "https://github.com/juanigarciadev/my-portfolio",
    badge: false,
    tag: "// Personal portfolio",
  },
];

export default projects;
